Add hook actionMainMenuModifier
PrestaShop/ps_mainmenu pull request #70
Opened 2023-06-05 14:30 UTC by bibips

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Allow main menu to be extended by other modules thanks a new hook `actionMainMenuModifier`. <br/>Thanks this hook it's possible to have menu items specific per customer by example.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | No issue
| How to test?  | Register hook `actionMainMenuModifier` and add or edit something into main menu

Hook usage :
```
    public function hookActionMainMenuModifier(array $hookParams)
    {
          $hookParams['menu']['children'][] = [
              'type' => 'link',
              'label' => $this->trans('Test', [], 'Modules.Test.Menu'),
              'url' => $this->context->link->getModuleLink($this->name, 'pickup'),
              'depth' => 1,
              'children' => [],
              'open_in_new_window' => "0",
              'page_identifier' => $this->trans('Test', [], 'Modules.Test.Menu'),
              'current' => false
          ];
    }
```

2023-06-19 08:31 UTC, M0rgan01 submitted a review, later dismissed

2023-06-19 09:07 UTC, Hlavtox commented
Wouldn't it be better if you could change the $menu variable instead? With this solution, you can display things only after the list, but cannot modify the items.

2023-06-19 11:25 UTC, bibips commented
> Wouldn't it be better if you could change the $menu variable instead? With this solution, you can display things only after the list, but cannot modify the items.

I like this Idea

2023-10-16 12:56 UTC, M0rgan01 commented
Sorry, I lost the thread! Yes it's ok for me :) You will need to add the new hook on the core side (in hook.xml file)

2023-10-16 12:56 UTC, M0rgan01 approved these changes

2023-10-16 13:24 UTC, Hlavtox commented
@M0rgan01 I think we shouldn't, the core should include no data or references to any modules I think.

2023-10-18 14:40 UTC, AureRita commented
Hi @bibips 

Thank you for your PR, I tested it and unfortunately this one doesn't works as expected as you can see : 

![image](https://github.com/PrestaShop/ps_mainmenu/assets/100699445/0d6d2c11-da77-49c1-ab98-6043cff003f3)

Indeed, the "use Hook;" doesn't seems to works and, because of that, the hook isn't accessible 

Thank you

2024-05-31 12:41 UTC, bibips commented
@AureRita Excuse me for the delay, I've remove  `use Hook;` as suggested

2024-06-12 10:49 UTC, boherm submitted a review, later dismissed

2024-11-18 06:47 UTC, jtraulle commented
This would be a great addition for external modules to be able to add links to the main menu.
Anything missing here @AureRita for this to be merged ?

2024-11-18 06:56 UTC, Hlavtox submitted a review, later dismissed
I don't see much value in this… isn't the sole purpose of menu that it's purely configurable by people?

Do you have any real use case for this hook?

2024-11-18 08:08 UTC, bibips commented
> I don't see much value in this… isn't the sole purpose of menu that it's purely configurable by people?
> 
> Do you have any real use case for this hook?

Hi @Hlavtox,

I created this hook to add or remove menu item according some criterias. By instance in my shop I have a menu item only available for a group of customer. Thanks to this hook, we can check if the customer is logged in or if the customer match some criterias (as country, device type, customer configuration, etc...) before making a menu item available.

Without this hook, we can't.

2025-02-21 16:32 UTC, bibips commented
Hi @Hlavtox,

Does this use case convince you of the hook's usefulness ?

2025-03-03 09:37 UTC, jolelievre approved these changes
Thanks @bibips

2025-03-21 09:23 UTC, paulnoelcholot commented
Hello @bibips,

I tried to test your PR, but I'm not sure I understood the steps to reproduce correctly. Can you please explain the steps to reproduce more precisely?

Thanks for your feedback!

2025-03-23 17:11 UTC, bibips commented
@paulnoelcholot I have created a module that use this new hook for your test. Thanks this module you can see a new menu item only if a customer is connected.
[actionmainmenumodifier.zip](https://github.com/user-attachments/files/19410411/actionmainmenumodifier.zip)

2025-03-23 17:16 UTC, Hlavtox requested changes
You also need to change config.xml if you are bumping version.

2025-03-24 07:47 UTC, bibips commented
@Hlavtox It's fixed

2025-03-24 09:09 UTC, Hlavtox approved these changes

2025-04-07 09:13 UTC, tleon approved these changes

2025-04-28 13:36 UTC, paulnoelcholot commented
Hello @bibips,

I tested your PR and it's good for me!

Thanks!

![image](https://github.com/user-attachments/assets/3b8886ac-00b6-4ecb-ad9e-469b8c2d1643)

2025-04-28 13:37 UTC, paulnoelcholot approved these changes

2025-04-28 14:52 UTC, merged

2025-04-28 14:52 UTC, boherm commented
Thanks @bibips!